### ISSUE TITLE
search: communities search by title with special characters causes problems

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-communities#104]
The search by title is not parsing unicode characters properly (and failing).

This works:
https://zenodo.org/communities/?p=Image+Knowledge+Gestaltung.+An+Interdisciplinary+Laboratory%2C+Cluster+of+Excellence+at+the+Humboldt-Universit

but adding extra character "ä" to the search yields not results:

https://zenodo.org/communities/?p=Image+Knowledge+Gestaltung.+An+Interdisciplinary+Laboratory%2C+Cluster+of+Excellence+at+the+Humboldt-Universit%C3%A4

**Comment by slint** [comment]
Closing because of module refactoring
