### ISSUE TITLE
Community members: broken pagination

### ISSUE THREAD

**Issue by anikachurilova** [inveniosoftware/invenio-communities#1145]
To reproduce: click on search icon

<img width="1394" alt="Screenshot 2024-06-12 at 17 12 36" src="https://github.com/inveniosoftware/invenio-communities/assets/61321254/eb16cfcd-cbe5-4ae3-bb75-bab8a15a2373">

**Comment by Samk13** [comment]
Duplicates of [#1136](https://github.com/inveniosoftware/invenio-communities/issues/1136)
