### ISSUE TITLE
models: add Alembic migrations

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-communities#156]

**Comment by lnielsen** [comment]
- [Invenio-DB documentation on Alembic](https://invenio-db.readthedocs.io/en/latest/alembic.html) (specifically the section "Adding alembic support to existing modules")
- Example of two recipes:
  - [Initial recipe to create a new branch for the current module](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/alembic/1095cdf9f350_create_records_branch.py)
  - [Second recipe that creates the database table](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/alembic/862037093962_create_records_tables.py)
  - [Example of how to test the recipe](https://github.com/inveniosoftware/invenio-records/blob/master/tests/test_alembic.py)
