### ISSUE TITLE
logos: add file size restriction

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-communities#18]
Add restriction on the file-size of the uploaded logo (1.5 Mb).
This depends on ``invenio-files-rest`` which should implement such feature, thus on the logo's part it's just a matter of intgrating with it during ``ObjectVersion`` initialization.

**Comment by jirikuncar** [comment]
Supported in Invenio-Files-REST since https://github.com/inveniosoftware/invenio-files-rest/commit/4bc591525b45ca70a192721686f8e35776dc17f8

**Comment by lnielsen** [comment]
This issue should not be closed as it is local to Inveiio-Communities AFAIK: https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/utils.py#L108

**Comment by jirikuncar** [comment]
`Bucket.query.filter_by(id=current_app.config['COMMUNITY_BUCKET_UUID).update(max_file_size=1.5*1024*1024)`?

**Comment by jirikuncar** [comment]
Closed via e7be28d3d163ffd997fc90ed4a397b08cb464716
