### ISSUE TITLE
Community ID input field accepts problematic values

### ISSUE THREAD

**Issue by max-moser** [inveniosoftware/invenio-communities#185]
Package version: 2.1.1

## Describe the bug
Upper-case letters in the community ID lead to issues; e.g. the community has no members defined, and it is not possible to join the community.
It is possible to visit the community page (with its ID in the URL converted to lower-case), but the community has no members and joining the community does not work either.

Further, some characters (e.g. forward slashes: '/') are also problematic if present in the ID, while others (e.g. bangs: '!') are fine.
It is not possible to visit these communities' pages, probably due to the slashes in the URL being interpreted by Flask.

Also, it is possible to create communities with IDs only containing whitespace, which are harder (but not impossible: using '%20' in the URL works) to access.
Otherwise, these communities work fine though.

## Steps to Reproduce
1. Go to the communities endpoint
2. Click on 'New community'
3. Fill ID field with problematic string
4. Fill out the other required fields with any values
5. Click on 'Submit'
6. See the error

## Expected behavior

The user's input for the ID field should be sanitized, or synthesized (e.g. via transformations on the community's title).

## Screenshots

In the screenshot:
1) Response for the redirect immediately after creation of community with ID containing upper-case letters
2) Response for access to this community by using the lower-cased ID in the URL
3) Attempt to join the community
![bug](https://user-images.githubusercontent.com/6437519/92246860-a658e380-eec6-11ea-9cde-98861eb5f700.png)

**Comment by lnielsen** [comment]
This has been fixed now. I'm no longer able to reproduce.
