### ISSUE TITLE
tests: REST API CRUD operations

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-communities#211]
- [ ] `/api/communities`
  - [x] `POST`
    - [x] Schema validation (required/optional fields, max length, enum values). Check also <https://github.com/inveniosoftware/docs-invenio-rdm/blob/master/docs/reference/rest_api.md#communities-preview> and specs in https://github.com/inveniosoftware/invenio-communities/issues/203
    - [x] Try creating a community with an `id` that already exists
    - [x] Try creating a community with an `id` that was deleted
    - [x] Correct link generated
  - [x] `GET`/`LIST`
    - [x] Response structure (`hits`, `aggregations`, `links`, etc. see <https://inveniordm.web.cern.ch/api/records>)
    - [x] Try to filter/sort/paginate (e.g. `?q=test`, page=1, size=5)
- [x] `/api/communities/<comid>`
  - [x] `GET`
  - [x] `PUT`
  - [x] `DELETE`

**Comment by effervescent-shot** [comment]
In `POST`
 - [ ] Try creating a community with an id that already exists
 - [ ] Try creating a community with an id that was deleted

Which `id` should be used? One given by user or one created after `POST`?
