### ISSUE TITLE
views: creation page

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-communities#224]
For logged-in user:

![image](https://user-images.githubusercontent.com/1814661/115228108-a635ed00-a111-11eb-946a-cade7bce629e.png)

**Comment by Glignos** [comment]
This will redirect to the rest of the form(settings) or to the community front page?

**Comment by slint** [comment]
> This will redirect to the rest of the form(settings) or to the community front page?

After creating the community, the user should be redirected to the community's frontpage.
