### ISSUE TITLE
emails: fix email sending

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#23]
Broken links

**Comment by krzysztof** [comment]
Can you give more details about this?

**Comment by lnielsen** [comment]
This email is not being sent: https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/templates/invenio_communities/new_upload_email.html
Also ``{{config.CFG_SITE_URL}}`` does not exists anymore.

**Comment by krzysztof** [comment]
Thanks :+1:
