### ISSUE TITLE
schema: fix validation messages

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-communities#240]
- [x] General
  - [x] Fix message returned by `_non_blank` to say something like `"Non empty string, less than {max} characters"`
  - [x] Check that multiple errors in the `metadata` (e.g. max length for both "title" and "description") are reported
  - [x] Double-check how errors are returned and displayed in the forms
- [x] While creating the community, 
  - [x] giving and title more than 250 char did not display any error message 
  - [x] giving and identifier more than 100 char did not display any error message

**Comment by effervescent-shot** [comment]
While creating the community, 
  - [ ] giving and identifier more than 100 char did not display any error message 
  - [ ] giving and title more than 250 char did not display any error message
