### ISSUE TITLE
ux: save buttons missing visual feedback on success/failure

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#282]
## Describe the bug

The save buttons on the community permissions pages have no visual feedback.

1. You cannot see you have changed a value and if it was saved or not
2. Once you click save, the user has no feedback if it was success or failure.

## Expected behavior

Option 1: Save button starts out in disabled state. If the user changes a dropdown it becomes enabled. They can then click save, and it goes back to disabled state on success.

Option 2: Once an operation was a success, display a small message green text message for a couple of seconds that that says "Saved".

## Screenshots (if applicable)

![Screenshot 2021-04-27 at 21 19 49](https://user-images.githubusercontent.com/1698163/116299701-4f2db900-a79e-11eb-9606-dc7f1a8290b5.png)

**Comment by lnielsen** [comment]
Same problem applies to the settings page:
![Screenshot 2021-04-27 at 22 26 29](https://user-images.githubusercontent.com/1698163/116308323-a5532a00-a7a7-11eb-8f2b-ba56bd7dd27e.png)

**Comment by lnielsen** [comment]
Do like ILS

**Comment by slint** [comment]
In the end the refresh in the is happening because to reflect the changes in the header (since the header is Jinja-based). We could use it though for the privileges maybe.
