### ISSUE TITLE
settings: logo upload styling

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#288]
## Describe the bug

1. DON'T change the title (even though it's shown on the screenshot - changed my mind ;-)
2. Replace the group icon, with the image placeholder instead (https://react.semantic-ui.com/elements/image/#types-image)

![Screenshot 2021-04-27 at 22 32 25](https://user-images.githubusercontent.com/1698163/116309312-e7c93680-a7a8-11eb-8328-45e249d58966.png)

**Comment by zzacharo** [comment]
Fixed in #294
