### ISSUE TITLE
settings: cannot rename when only changing capitalisation

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#290]
## Steps to Reproduce

1. Create a new community with an identifier, e.g. ``Zenodo``.
2. Now, try to rename the identifier to ``zenodo`` (lower-case z).

## Expected behavior

That I'm able to fix upper/lower case issues in the identifier.

**Comment by slint** [comment]
Closing since now all input gets converted to lowercase (thus there's no way to create a community with any uppercase letters)
