### ISSUE TITLE
installation: remove invenio-records-permissions from setup.py

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#347]
https://github.com/inveniosoftware/invenio-communities/blob/v2.3.2/setup.py#L69

Instead we rely on invenio-rdm-records.

**Comment by ppanero** [comment]
Check properly bootstrapping an InvenioRDM v4 instance. I recall adding this pin because otherwise the locking process was breaking due to an incoming version of `>0.12` (from records-resources somehow?)
