### ISSUE TITLE
"Renaming" doesn't rename

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-communities#376]
Package version (if known): 7

## Describe the bug
The terminology "rename community" is used to mean "change a community's id", but reads as "change its title". This is confusing in the code and docs. See https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/assets/semantic-ui/js/invenio_communities/settings/profile/RenameCommunityButton.js#L16 .

**Comment by ppanero** [comment]
Fell into this too
