### ISSUE TITLE
rest: serialisation should include self, prev and next links

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#39]
See Records-REST for details. 
HTML link should also be included.
Should also be added in the HTTP Headers (https://tools.ietf.org/html/rfc5988)

**Comment by JavierDelgadoFernandez** [comment]
@lnielsen HTML link to the page or to the details of each community?

**Comment by lnielsen** [comment]
the html link should go to the "frontage" of each community i.e. /communities/<id>/
