### ISSUE TITLE
Identity: Provide community roles to the current identity

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#411]
When a user logs in, they need to be provided with their community role needs.

Details in 
- https://codimd.web.cern.ch/FkKsoasfQtGlIApR4m_osg
- https://codimd.web.cern.ch/g76618tTSw-YT9akFg_pgw

**Comment by fenekku** [comment]
Dealt with in blocked https://github.com/inveniosoftware/invenio-communities/pull/428
