### ISSUE TITLE
Community details: list of members

### ISSUE THREAD

**Issue by NRodriguezcuellar** [inveniosoftware/invenio-communities#452]
As a user i want to have an overview of the members inside a certain community

Proposed in https://codimd.web.cern.ch/f3a7_DoqSfed6m_VMa649A#List-of-members

It should show different versions depending on who is accessing the list

- owner/manager
- curator/member
- anonymous

**Comment by jrcastro2** [comment]
Closed in favor of https://github.com/inveniosoftware/invenio-communities/issues/456 and https://github.com/inveniosoftware/invenio-communities/issues/458
