### ISSUE TITLE
Community details: create requests tab

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-communities#453]
Similar to the “My dashboard - list requests”, a community should have a page with all requests for the community.

![upload_fb44410934d87ffc73d60704c5689c42](https://user-images.githubusercontent.com/2089455/157645259-2ddf72c9-27f4-4fa7-82cb-8e709a175f54.png)

**Comment by Pineirin** [comment]
Duplicated: https://github.com/inveniosoftware/invenio-communities/issues/454.
