### ISSUE TITLE
Backend: Send email notifications

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#502]
Send emails
	- New invitation
	- New submission (who to notify in a community)
	- New comment
	- Accepted submission
	- Declined invitation

**Comment by kpsherva** [comment]
https://github.com/inveniosoftware/rfcs/pull/56/files#diff-9e678d88eadb1c15aa463a0269c9e4d36b009f4dd379099d8860ea8e99c831b1

**Comment by rekt-hard** [comment]
To test locally:
- install https://github.com/inveniosoftware/invenio-requests/pull/257
- install https://github.com/inveniosoftware/invenio-rdm-records/pull/990
- create community
- create draft record
- select community
- save draft

In the console, there will be the output of the email.
It should be there 3 times, but is usually only there once (https://github.com/inveniosoftware/invenio-requests/pull/257/files#diff-b87cf48eb90b0b83fc461049a08076933bb1c2e3ccb8c6a1501412735ede6119R41-R50)
