### ISSUE TITLE
Invitate members: Remove frontend timeout 

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-communities#522]
In [InvitationsMembersModal.js](https://github.com/inveniosoftware/invenio-communities/pull/516/files#diff-de26401b713caabbe38eb2e8d5f68aa44d1860f74855251904c61be3ab6d0b84) we added a timeout that should be removed as soon as the backend implements it.

**Comment by ntarocco** [comment]
Implemented
