### ISSUE TITLE
Backend: Invitations should not be returned in member search

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-communities#592]
## Steps to Reproduce

1. Create a community and invite a new user (without them accepting/rejecting/cancelling)
2. Perform a member search `` /api/communities/9ff55ff4-767b-427f-86cd-9429211392ec/members``.
3. See that the invited member is part of the listed members.

## Expected behavior

Invitations should not be part of th list of members.

## Fix

<img width="793" alt="Screenshot 2022-05-04 at 11 50 13" src="https://user-images.githubusercontent.com/1698163/166659677-1b21ae5e-77f5-487d-b98f-c602c4d09d87.png">

**Comment by ntarocco** [comment]
Fixed in: https://github.com/inveniosoftware/invenio-communities/pull/583
