### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-communities#61]
- check existing API functionality
- add missing important API functionality
- check API function signatures and parameters
- enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- plug API functions to existing docs

**Comment by mittagessen** [comment]
Is there any ongoing work on this? Currently the API is missing any curation functionality which seems to be a rather large oversight.

**Comment by lnielsen** [comment]
It's not an oversight, just a prioritization we had to take when we rewrote Invenio v3 and launched Zenodo on v3. As mention on Gitter this is scheduled for a big update in the coming half year

**Comment by slint** [comment]
Closing because of module refactoring
