### ISSUE TITLE
models: rename foreign keys from `id_*` to `*_id`

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-communities#63]
- following discussion in https://github.com/inveniosoftware/invenio-groups/issues/39#issuecomment-238219783
- addresses #61 
## 

cc @lnielsen

**Comment by lnielsen** [comment]
Fine with me - I never liked the ``id_*`` naming pattern.

**Comment by slint** [comment]
Closing because of module refactoring
