### ISSUE TITLE
ui: community logo displayed awkwardly

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-communities#659]
in the communities view, the logo has a white background around it, inside the card. The logo should fill the space
<img width="342" alt="Screenshot 2022-05-13 at 11 10 44" src="https://user-images.githubusercontent.com/38131488/168251647-c829941c-13a8-4e8a-890f-bea9ea2fe330.png">

**Comment by jennur** [comment]
For it to always fill the whole space, we'll either have to accept different sized image-containers (ie. the horizontal line + the text beneath the image will not be in the same position on all the cards), or we'll need to set a requirement for the dimensions on the image uploader.
