### ISSUE TITLE
bibupload dependency removal

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-communities#7]
The model currently depends on bibupload:
 - https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/models.py#L349
 - https://github.com/inveniosoftware/invenio-communities/blob/master/invenio_communities/models.py#L361

It should be the last modules and then I can remove it from invenio with my PR inveniosoftware/invenio#3470
Can we find a way to remove this dependency?

**Comment by lnielsen** [comment]
Yes, leave invenio-communities in a broken state (and don't install it by default with Invenio). Once I move Zenodo to 2.2 (or what the release will be called) I will fix it.
