### ISSUE TITLE
communities: add `restricted` label to the community header if the community is restricted

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-communities#732]
- [x] add `restricted` label in community header
- [x] add more information in the community selection modal (deposit)
<img width="958" alt="Screenshot 2022-06-20 at 11 18 29" src="https://user-images.githubusercontent.com/38131488/175896100-37941787-55fa-4f42-a4c3-fe54c4c4f678.png">

**Comment by alejandromumo** [comment]
After discussion with @jennur , we did not add anything else to the community item list in the deposit form.

The attributes not being shown are: 

- URL : it could be missleading as we already have a link next to the community name (`View community`). 
- Organizations: it could get cluttered.

Nonetheless if there is a strong argument on why any of the above should be included, I can add it.
