### ISSUE TITLE
community: Validation error on edit correct url

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-communities#764]
Package version (if known): v2.8.7

## Describe the bug
When editing a community, if an user adds a wrong URL and saves it he/she will get an error. After doing so if a correct URL is introduced and saved immediately it will still show the error and the save button is disabled until the field looses focus

## Steps to Reproduce
1. Go to "New community"
2. Fill in the required fields of the  form
3. Add a non-valid url in the URL field 
4. Click "Save" button
5. See validation error
6. Update url to a valid value
7. Click "Save" button
8. Still see validation error

## Expected behavior
Record should be correctly saved after introducing a valid URL.

## Screenshots (if applicable)

https://user-images.githubusercontent.com/15194802/178260855-a031d5ba-3487-4bf6-a249-dadadc230902.mp4

**Comment by kpsherva** [comment]
the url is not considered as valid without `www` in the url
