### ISSUE TITLE
api: create an Community.oaiset relationship

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-communities#78]
As discussed here: https://github.com/inveniosoftware/invenio-communities/pull/76#discussion_r80249385

It would be nice to set up an relationship between OAISet and Community instead of using a model property:

```
if COMMUNITIES_OAI_ENABLED:
    from invenio_oaiserver.models import OAISet
    Community.oaiset = db.relationship(
        OAISet, primaryjoin=OAISet.spec==Community.oaiset_spec, viewonly=True)
```

**Comment by slint** [comment]
Closing because of module refactoring
