### ISSUE TITLE
public record in restricted community

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-communities#818]
Package version (if known): invenio-app-rdm v10? (https://inveniordm.web.cern.ch 2022-10-17)

## Describe the bug
I was able to have a public record in a restricted community.

## Steps to Reproduce
1. Create a "public" community.
2. Publish a fully "public" record within this community.
3. Change the community visibility to "restricted"
4. See public record within a restricted community

## Expected behavior

As described here:
https://discord.com/channels/692989811736182844/704625518552547329/1030462802491617312
if a community contains public records the community cannot be changed to restricted 

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/74763324/196159668-64d6843d-1046-4460-95ee-469f10c923bf.png)
![image](https://user-images.githubusercontent.com/74763324/196159953-e9f9a90c-11fe-4b06-995c-1bd9726b9acd.png)

**Comment by kpsherva** [comment]
The solution needs to be discussed before starting the implementation
