### ISSUE TITLE
Featured communities component

### ISSUE THREAD

**Issue by jennur** [inveniosoftware/invenio-communities#819]
Create a slideshow component for featured communities, similar to the one in Zenodo:
<img width="1351" alt="Screenshot 2022-10-17 at 16 13 18" src="https://user-images.githubusercontent.com/21052053/196200114-73adf274-92ec-45ea-95f3-53ac6984ffca.png">

Related to:
- https://github.com/inveniosoftware/invenio-app-rdm/issues/1932 and
- https://github.com/zenodo/zenodo-rdm/issues/47

**Comment by ntarocco** [comment]
@jennur see comment from Alex [here](https://github.com/inveniosoftware/invenio-app-rdm/issues/1932#issuecomment-1288514420): does this follow his solution?
