### ISSUE TITLE
models: use UUID for community ID and move the current ID to a separate field

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-communities#84]
As discussed IRL with @lnielsen and during DR meeting.
## Why:

**Reason 1:**
Current design require that every reference needs to be updated when the community is renamed.

**Reason 2**
B2Share would like to use this module. It is quite probable that it will have to support the migration of a community from one server to another. In order to avoid conflicts it would be needed to have unique identifiers for Communities.

**Reason 3**
B2Share builds endpoints on top of the communities REST API endpoint. One of those endpoints is the communities' schemas /api/communities/<ID>/schemas/<version>.
If the community is renamed every record cannot validate anymore. We could update the current records but all the previous versions become hard to work with.

**Reason to keep a user friendly id in a separate field:**
Zenodo has an endpoint for each community. Thus it needs a unique human friendly name for each community.
## Who needs it:
- Zenodo for reason 1
- B2Share for reasons 1 and 2

**Comment by jirikuncar** [comment]
### Proposal

The community renaming is equivalent of changing nickname on GitHub. Hence, I would propose that "renaming" community will create a redirect from the old one.

Conflict resolution and migration is completely different use-case which you don't solve by introducing UUID for each community because at the end the human-friendly urls will point to duplicates. Moreover you will have the same problem in Elasticsearch if you would like to provide faceted search based on community name. You can force all B2Share instances to have unique prefix for their community (we can add this configuration) or move to solution using PIDStore.

**Comment by nharraud** [comment]
@jirikuncar The idea is not to solve the issue. It is to make migrations as easy as possible. There will always be conflicts (example: user accounts id which have an integer as ID), but using UUIDs will make conflicts less frequent and simplify migrations: one of the community would change its name but the records would not need any modification. The record history would still make sense as it would be possible to know in what community records where before without guessing previous community names.

PIDStore are needed for records as there are many types of persistent identifiers for publications (DOI, ePIC PIDs, etc...). Whereas for communities I am not sure that we will need something else than one UUID and a name.
However is one use case which could justify it, if the communities also have ORCID IDs or some other kind of IDs. If you think that this is a requirement for invenio-communities then it makes sense. B2Share does not have this requirement for now.

**Comment by jirikuncar** [comment]
Another plus of using PIDStore to keep a track of community names would be a "merging" of communities. For preservation purposes it is IMHO better to keep the community name as part of the record to express the fact that at the given time the community had that identifier.

That said, I would be for UUID if community name becomes PID.

**Comment by nharraud** [comment]
I added a third reason why we need stable URLs for communities.

I discussed with @ludmilamarian yesterday to see how CDS is handling community renaming. In fact they try to never change the URLs. When a community is renamed they just change the name displayed on the pages, not the URL. When a community is merged/split, they just close the previous community and create a new one. That way the bookmarks still work and people don't have to guess where a community disappeared.

She also mentioned that with this approach (names in URLs without renaming) another problem was appearing. The URL names at some point didn't match the new names displayed on the page. This was confusing some users.

For these reasons I would still go for a UUID in the URLs, be it from a PID store or just a field in the Community model.

cc @krzysztof

**Comment by lnielsen** [comment]
Back from vacation :-)

### Identifiers

I think it makes sense to have a uuid/integer based unique identifier for communities. This is also analogous to how GitHub handles repositories - (id, name, full_name - see https://api.github.com/repos/inveniosoftware/invenio-communities). If you rename a repo the id stays the same, and name/full_name changes, this makes integration with github a lot more reliable in e.g. invenio-github. I.e. I think we have the following two identifiers

- community id: uuid (new)
- community slug: current community id (e.g ``biosyslit``)

### Record metadata and indexing
Would a solution work were we only store the community id in the record, and when indexing a record expanded the community ids to slugs?

Pros:
- Renaming of a community slug would not require record metadata updates.
- Faceting and searching like ``communities:biosyslit`` would still work with ES query parser, and a renaming would just require reindexing affected records (i.e. no extra record metadata revision for large number of records)
Cons:
- Community slug is not part of the record metadata for preservation purposes

### PIDStore vs Community model
I'm somewhat undecided on this. It would introduce some extra complexity which might be overkill for communities, on the other hand we're getting redirection for renamed communities for free via the resolver.

**Comment by nharraud** [comment]
I also think that it could be also possible to have a separate table to join communities and records. As @krzysztof said last time we discussed, the CPU overhead should not be too big as the tables won't be joined so often.

I would just have one question first: I have heard some mentions of sharding the records table in the past but I don't know if we actually have anybody doing it or if it was just an idea. If this is not one of our requirements/priority it is not an important question. Otherwise I wonder what cost this would imply.

**Comment by jirikuncar** [comment]
> it could be also possible to have a separate table to join communities and records.

We have abandoned this since it causes more problems when you are merging records or re-linking their PID.

**Comment by krzysztof** [comment]
@jirikuncar what about m2m between PID and Community?

**Comment by nharraud** [comment]
@lnielsen @krzysztof @jirikuncar So what do we decide regarding this issue? PIDStore or not? UUID in records or not?
I would tend to go with the initial suggestion (#85) and add PIDStore later if needed for UI (REST API should never need redirection as it uses UUIDs).

**Comment by lnielsen** [comment]
@nharraud How urgent is a decision on this on your side?

**Comment by nharraud** [comment]
@lnielsen It can wait a few weeks as I don't think that we will have time to integrate invenio-communities before the beginning of December. At that point however it will have a high priority for us as it's blocking integration.

**Comment by lnielsen** [comment]
@nharraud Perhaps we could schedule a sprint together for beginning of December to work on communities (and naturally integration with our services)?

**Comment by slint** [comment]
Closing because of module refactoring
