### ISSUE TITLE
Skip notifications on specific community/user setting

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-communities#864]
It should be possible to disable notifications in one (or all?) of the following manners:

- on the entire community level, i.e. so that none of the community members receive notifications of submission requests and member invitations. This should extend to comments/actions (i.e. `RequestEvent`s) for these requests.
- on the community member level, so that a user can set to say if the want to receive notifications or not for this community

> TODO: Some use-cases might help to explain this better

**Comment by slint** [comment]
Mockup for user notifications preferences: 

![image](https://user-images.githubusercontent.com/1814661/229537879-5b996ee2-79b4-4e16-aa73-b7ea18ffc218.png)

**Comment by lnielsen** [comment]
Thanks for the mockups, here's some quick feedback:
- Text: Overall needs a bit of update - e.g. "Allow receiving notifications" I would call something like "Notify me" or similar.
- The communities box should not be inside the notifications box, it should be two separate boxes.
- I would add in the top box how people receive notifications - something along the lines of "Notifications email: lars.holm.nielsen@cern.ch" with some help text along the lines of "We use your primary email address to notify you on. You can change your email on the your <link>profile settings<link>".
- Dropdown: None -> Disable

Some questions:
- Are we able to implement the "per community notification"? Where do we technically store this information?

**Comment by slint** [comment]
Mockup updated

![image](https://user-images.githubusercontent.com/1814661/230018459-c03958e2-72c9-452a-9061-e1c851bf0864.png)

> * Text: Overall needs a bit of update - e.g. "Allow receiving notifications" I would call something like "Notify me" or similar.

Done, simplified some other texts as well. Still not very happy with everything, but maybe another set of fresh eyes will help.

> * The communities box should not be inside the notifications box, it should be two separate boxes.

I also added a top-level toggle for disabling community notifications in general (could be useful for e.g. a bot account). The communities list feels a bit "unbounded" now, but we'll have to see how we translate this in SemanticUI also.

> * I would add in the top box how people receive notifications - something along the lines of "Notifications email: [lars.holm.nielsen@cern.ch](mailto:lars.holm.nielsen@cern.ch)" with some help text along the lines of "We use your primary email address to notify you on. You can change your email on the your profile settings".

Agree. Currently we don't actually have a way to store multiple email addresses (maybe via `UserIdentities`?), but it's good to show it for clarity and having it in mind for the future.

> * Are we able to implement the "per community notification"? Where do we technically store this information?

There are two candidates at the moment for storing this information:

- `User.preferences` in some flexible dictionary structure defined by the Marshmallow schema.
- `CommunityMember.json` is currently unused and feels right in terms of placement. It does though split the user settings information across many places.
