### ISSUE TITLE
Direct publish

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-communities#871]
A user can directly publish to a specific community without review if the community has enabled that setting. The setting is connected with a specific permission that can be configured per instance.

**Comment by zzacharo** [comment]
**Update**: A user can directly publish to a specific community without review if the community has enabled that setting. The setting is connected with a specific permission that can be configured per instance.

**Comment by zzacharo** [comment]
RFC: https://codimd.web.cern.ch/5x04qP64RNCxlUFs85WXvQ

**Comment by zzacharo** [comment]
Draft PRs
- https://github.com/inveniosoftware/invenio-communities/pull/883
- https://github.com/inveniosoftware/invenio-rdm-records/pull/1169
- https://github.com/inveniosoftware/invenio-app-rdm/pull/2056
- https://github.com/inveniosoftware/react-invenio-deposit/pull/614
