### ISSUE TITLE
UI: Community approval buttons on record landing page

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-communities#873]
- [ ] propose ux design for placig the approval/decline pending community request

Prerequisites:  records can be published without priorly selected community
- [ ] implement the proposed solution

Currently on zenodo (above the red frame):
![](https://user-images.githubusercontent.com/1814661/180170937-0bdbbc5a-d0d1-4480-aeec-36c928821ecf.png)

**Comment by jennur** [comment]
# Layout suggestions

## Community management modal (removal)
![community-management_version-1_closed](https://user-images.githubusercontent.com/21052053/215427090-951a9895-49cd-43cc-bafa-627a44ad2ece.png)

![community-management_version-1_open](https://user-images.githubusercontent.com/21052053/215427106-17e408ae-353e-4692-8b78-7e82057f4aec.png)

![community-management_version-1_open-popup](https://user-images.githubusercontent.com/21052053/215427103-be659f0c-f351-4a90-98e9-9e34adf6a7f0.png)


## Community management in sidebar (removal + approval https://github.com/inveniosoftware/invenio-communities/issues/873)
![community-management_version-2](https://user-images.githubusercontent.com/21052053/215427643-cee48b88-4b03-4d9e-a801-43259616761c.png)
