### ISSUE TITLE
Count members and records of community

### ISSUE THREAD

**Issue by anikachurilova** [inveniosoftware/invenio-communities#935]
Integrate information about amount of members and records of the community for the delete communinty modal

Before:
<img width="1552" alt="Screenshot 2023-03-29 at 14 00 51" src="https://user-images.githubusercontent.com/61321254/228553426-cf9636b5-597b-41cb-b7b6-9a2b4e7cd88e.png">

After:
<img width="536" alt="Screenshot 2023-03-29 at 15 28 52" src="https://user-images.githubusercontent.com/61321254/228553494-8d31d864-11d4-4f79-be1c-46218a02e9ea.png">

**Comment by kpsherva** [comment]
hints:

check the REST API of members service and see how you can dump this information in settings page

probably you can dump this information in the view corresponding to the settings page so you have them available already
