### ISSUE TITLE
Add support for multiple curators

### ISSUE THREAD

**Issue by nuest** [inveniosoftware/invenio-communities#97]
_(Hope this is the right repo, I apprecciate a pointer if this is the wrong place to suggest this.)_

It would be great if multiple people could administer a community/collection.

**Comment by lnielsen** [comment]
This is definitely on the road map. Exactly when it will land I can't say for sure yet, but probably either Q2 or Q3 this year.

**Comment by slint** [comment]
Closing because of module refactoring
